# name: Lighthouse
# on: [push, pull_request]
# jobs:
#   lighthouse:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14.x" 
#       - name: Capture Vercel Preview URL
#         uses: aaimio/vercel-preview-url-action@v1
#       - run: |
#           yarn install
#       - name: run Lighthouse CI
#         run: |
#           yarn global add @lhci/cli@0.8.x
#           lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
#         # We need to integrate https://github.com/zentered/vercel-preview-url to use this build instead of building in this test
#         with:
#         urls: |
#           ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
#         uploadArtifacts: true
#         temporaryPublicStorage: true
  
#         env:
#           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
#           CONTENTFUL_ENVIRONMENT: ${{secrets.CONTENTFUL_ENVIRONMENT}}
#           CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
#           CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
